name: ar_cademy
description: "ARcademy is a mobile application developed using the Flutter framework that leverages Augmented Reality (AR) technology to bring the study of human anatomy to life. The application allows users to explore detailed 3D models of the human body in real-world environments through the lens of their mobile devices."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.3.10
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.9
  smooth_page_indicator: ^1.1.0
  firebase_core: ^2.25.3
  firebase_auth: ^4.17.3
  dartz: ^0.10.1
  flutter_easyloading: ^3.0.5
  bot_toast: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section
  assets:
    - assets/icons/
    - assets/images/
    - assets/fonts/

  # To add custom fonts to your application, add a fonts section here
  fonts:
    - family: Jakarta
      fonts:
        - asset: assets/fonts/PlusJakartaSans-ExtraBold.ttf
          style: normal
          weight: 800

        - asset: assets/fonts/PlusJakartaSans-Bold.ttf
          style: normal
          weight: 700

        - asset: assets/fonts/PlusJakartaSans-SemiBold.ttf
          style: normal
          weight: 600

        - asset: assets/fonts/PlusJakartaSans-Medium.ttf
          style: normal
          weight: 500

        - asset: assets/fonts/PlusJakartaSans-Regular.ttf
          style: normal
          weight: 400